services:
  db:
    image: mysql:8.0
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
  web:
    build: .
    # ここに ports を追加します
    ports:
      - "3000:3000"
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/myapp
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: "725d76df6bf88b9bfe41343bbe26e275241d331a6982f3df726b4b448d6dccf6f8fa31051b41a0403b5faf952701d1f305ebc7084d7047e857f8b9bb1b9425cd"
      TZ: Asia/Tokyo
      MYSQL_PASSWORD: password
      DB_HOST: db
    depends_on:
      db:
        condition: service_started
volumes:
  mysql_data:
