services:
  db:
    image: mysql:8.0
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
  web:
    build: .
    # ここに ports を追加します
    ports:
      - "3000:3000"
    command: tail -f /dev/null
    volumes:
      - .:/myapp
    environment:
      TZ: Asia/Tokyo
      MYSQL_PASSWORD: password
      DB_HOST: db
    depends_on:
      db:
        condition: service_started
volumes:
  mysql_data:
